import type { DiagnosisReport } from "../types/dashboard";

export const DEMO_MOCKS: Record<string, DiagnosisReport> = {
  "2ab005f0-5087-4943-ab3b-9ca2e22d4d2b": {
    "jobId": "2ab005f0-5087-4943-ab3b-9ca2e22d4d2b",
    "device_id": "DEMO_normal_device.txt",
    "created_at": "2026-09-20T17:00:00Z",
    "completed_at": "2026-09-20T17:00:00Z",
    "connection_method": "demo",
    "battery_health_pct": null,
    "severity": "LOW",
    "root_cause": "normal",
    "offending_package": null,
    "wakelock_offender": false,
    "cpu_offender": false,
    "crash_count_24h": 0,
    "thermal_events": 0,
    "memory_free_pct": 45,
    "storage_utilization_pct": 65,
    "diagnosis_summary": "Your device appears to be in good health with no significant hardware or software issues detected.",
    "recommended_action": "none",
    "action_label": "No action required \u2014 device is healthy",
    "adb_command": null,
    "evidence_snippets": []
  },
  "2351a976-c1ed-4480-bd74-da701f556cd9": {
    "jobId": "2351a976-c1ed-4480-bd74-da701f556cd9",
    "device_id": "DEMO_rogue_app.txt",
    "created_at": "2026-09-20T17:00:00Z",
    "completed_at": "2026-09-20T17:00:00Z",
    "connection_method": "demo",
    "battery_health_pct": null,
    "severity": "CRITICAL",
    "root_cause": "rogue_process",
    "offending_package": "com.facebook.katana",
    "wakelock_offender": true,
    "cpu_offender": true,
    "crash_count_24h": 5,
    "thermal_events": 0,
    "memory_free_pct": 45,
    "storage_utilization_pct": 65,
    "diagnosis_summary": "The process 'com.facebook.katana' is consuming 85.0% of CPU cycles, preventing the device from entering low-power states and accelerating battery drain. Force-stopping or disabling this application should resolve the drain.",
    "recommended_action": "disable_package",
    "action_label": "Disable the offending application",
    "adb_command": null,
    "evidence_snippets": [
      "85.0% com.facebook.katana",
      "Wakelock com.facebook.katana/.ForegroundService"
    ]
  },
  "b4d66801-65b1-4ec6-8cd1-7a195ab44de1": {
    "jobId": "b4d66801-65b1-4ec6-8cd1-7a195ab44de1",
    "device_id": "DEMO_overheating.txt",
    "created_at": "2026-09-20T17:00:00Z",
    "completed_at": "2026-09-20T17:00:00Z",
    "connection_method": "demo",
    "battery_health_pct": null,
    "severity": "HIGH",
    "root_cause": "thermal_throttling",
    "offending_package": null,
    "wakelock_offender": false,
    "cpu_offender": false,
    "crash_count_24h": 0,
    "thermal_events": 2,
    "memory_free_pct": 45,
    "storage_utilization_pct": 65,
    "diagnosis_summary": "The device recorded 2 thermal throttling event(s), causing the CPU to be clocked down to reduce heat. The primary heat source appears to be 'a background process'. Consider force-stopping it.",
    "recommended_action": "force_stop_package",
    "action_label": "Force-stop the overheating application",
    "adb_command": null,
    "evidence_snippets": []
  },
  "43d7f85c-1557-4693-87be-da406f54644e": {
    "jobId": "43d7f85c-1557-4693-87be-da406f54644e",
    "device_id": "DEMO_battery_degraded.txt",
    "created_at": "2026-09-20T17:00:00Z",
    "completed_at": "2026-09-20T17:00:00Z",
    "connection_method": "demo",
    "battery_health_pct": 63,
    "severity": "HIGH",
    "root_cause": "battery_degradation",
    "offending_package": null,
    "wakelock_offender": false,
    "cpu_offender": false,
    "crash_count_24h": 0,
    "thermal_events": 0,
    "memory_free_pct": 45,
    "storage_utilization_pct": 65,
    "diagnosis_summary": "Your battery has degraded to approximately 63% of its original capacity (2820 mAh vs. the factory design of 4500 mAh).",
    "recommended_action": "replace_battery",
    "action_label": "Replace the battery \u2014 hardware service required",
    "adb_command": null,
    "evidence_snippets": [
      "Estimated: 2820 mAh / Design: 4500 mAh"
    ]
  }
};
